// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lakes.sql

package db

import (
	"context"
)

const countLakes = `-- name: CountLakes :one
SELECT count(*) FROM lakes
`

func (q *Queries) CountLakes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLakes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const upsertLakeByGeoCode = `-- name: UpsertLakeByGeoCode :one
INSERT INTO lakes (geo_code, name, county, elev_m, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (geo_code) DO UPDATE
SET county     = COALESCE(EXCLUDED.county, lakes.county),
    elev_m     = COALESCE(EXCLUDED.elev_m, lakes.elev_m),
    updated_at = now()
RETURNING id
`

type UpsertLakeByGeoCodeParams struct {
	GeoCode *string  `json:"geo_code"`
	Name    string   `json:"name"`
	County  *string  `json:"county"`
	ElevM   *float64 `json:"elev_m"`
}

// Seed/refresh a lake from the stocking feed, keyed by WDFW geo_code. Name is
// set once on insert (NHD supplies the canonical GNIS name in phase 2b); on
// conflict we only refresh county/elevation, never clobber an existing name.
func (q *Queries) UpsertLakeByGeoCode(ctx context.Context, arg UpsertLakeByGeoCodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertLakeByGeoCode,
		arg.GeoCode,
		arg.Name,
		arg.County,
		arg.ElevM,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
