// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CatchLog struct {
	ID              int64              `json:"id"`
	LakeID          int64              `json:"lake_id"`
	TripStart       pgtype.Timestamptz `json:"trip_start"`
	TripEnd         pgtype.Timestamptz `json:"trip_end"`
	AnglerCount     int32              `json:"angler_count"`
	Species         *string            `json:"species"`
	Count           int32              `json:"count"`
	PredictionShown []byte             `json:"prediction_shown"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Condition struct {
	ID               int64              `json:"id"`
	LakeID           int64              `json:"lake_id"`
	ValidAt          pgtype.Timestamptz `json:"valid_at"`
	HorizonH         int32              `json:"horizon_h"`
	AirTempC         *float64           `json:"air_temp_c"`
	WaterTempC       *float64           `json:"water_temp_c"`
	PressureHpa      *float64           `json:"pressure_hpa"`
	PressureTendency *float64           `json:"pressure_tendency"`
	WindMps          *float64           `json:"wind_mps"`
	CloudPct         *float64           `json:"cloud_pct"`
	SolunarState     *string            `json:"solunar_state"`
	Confidence       *float64           `json:"confidence"`
	ComputedAt       pgtype.Timestamptz `json:"computed_at"`
}

type Lake struct {
	ID                 int64              `json:"id"`
	WdfwID             *string            `json:"wdfw_id"`
	Name               string             `json:"name"`
	County             *string            `json:"county"`
	Geom               interface{}        `json:"geom"`
	Centroid           interface{}        `json:"centroid"`
	AreaM2             *float64           `json:"area_m2"`
	ElevM              *float64           `json:"elev_m"`
	DepthMaxM          *float64           `json:"depth_max_m"`
	DepthMeanM         *float64           `json:"depth_mean_m"`
	MorphSource        *string            `json:"morph_source"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	GeoCode            *string            `json:"geo_code"`
	LakeType           *string            `json:"lake_type"`
	ConfidenceNowcast  *float64           `json:"confidence_nowcast"`
	ConfidenceForecast *float64           `json:"confidence_forecast"`
}

type SpeciesPresence struct {
	ID         int64              `json:"id"`
	LakeID     int64              `json:"lake_id"`
	Species    string             `json:"species"`
	Confidence float64            `json:"confidence"`
	Source     string             `json:"source"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type StationOb struct {
	ID        int64              `json:"id"`
	StationID int64              `json:"station_id"`
	ValidAt   pgtype.Timestamptz `json:"valid_at"`
	Var       string             `json:"var"`
	Value     float64            `json:"value"`
}

type StockingEvent struct {
	ID           int64              `json:"id"`
	LakeID       *int64             `json:"lake_id"`
	Species      string             `json:"species"`
	Count        *int32             `json:"count"`
	SizeClass    *string            `json:"size_class"`
	PlantDate    pgtype.Date        `json:"plant_date"`
	Hatchery     *string            `json:"hatchery"`
	SocrataRowID string             `json:"socrata_row_id"`
	IngestedAt   pgtype.Timestamptz `json:"ingested_at"`
}

type WeatherStation struct {
	ID         int64              `json:"id"`
	Source     string             `json:"source"`
	ExternalID string             `json:"external_id"`
	Geom       string             `json:"geom"`
	ElevM      float64            `json:"elev_m"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
