// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: predict.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const conditionsForLake = `-- name: ConditionsForLake :many
SELECT valid_at, horizon_h, air_temp_c, water_temp_c, pressure_hpa, pressure_tendency, wind_mps, cloud_pct, confidence
FROM conditions
WHERE lake_id = $1
ORDER BY horizon_h
`

type ConditionsForLakeRow struct {
	ValidAt          pgtype.Timestamptz `json:"valid_at"`
	HorizonH         int32              `json:"horizon_h"`
	AirTempC         *float64           `json:"air_temp_c"`
	WaterTempC       *float64           `json:"water_temp_c"`
	PressureHpa      *float64           `json:"pressure_hpa"`
	PressureTendency *float64           `json:"pressure_tendency"`
	WindMps          *float64           `json:"wind_mps"`
	CloudPct         *float64           `json:"cloud_pct"`
	Confidence       *float64           `json:"confidence"`
}

// Full nowcast+forecast series for a lake, ordered by horizon.
func (q *Queries) ConditionsForLake(ctx context.Context, lakeID int64) ([]ConditionsForLakeRow, error) {
	rows, err := q.db.Query(ctx, conditionsForLake, lakeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConditionsForLakeRow
	for rows.Next() {
		var i ConditionsForLakeRow
		if err := rows.Scan(
			&i.ValidAt,
			&i.HorizonH,
			&i.AirTempC,
			&i.WaterTempC,
			&i.PressureHpa,
			&i.PressureTendency,
			&i.WindMps,
			&i.CloudPct,
			&i.Confidence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lastCatchablePlant = `-- name: LastCatchablePlant :one
SELECT plant_date, species
FROM stocking_events
WHERE lake_id = $1 AND size_class IN ('legals', 'adult')
ORDER BY plant_date DESC
LIMIT 1
`

type LastCatchablePlantRow struct {
	PlantDate pgtype.Date `json:"plant_date"`
	Species   string      `json:"species"`
}

// Most recent catchable/legal-size trout plant for a lake — drives the dominant
// "days since last catchable plant" bite factor.
func (q *Queries) LastCatchablePlant(ctx context.Context, lakeID *int64) (LastCatchablePlantRow, error) {
	row := q.db.QueryRow(ctx, lastCatchablePlant, lakeID)
	var i LastCatchablePlantRow
	err := row.Scan(&i.PlantDate, &i.Species)
	return i, err
}

const primarySpecies = `-- name: PrimarySpecies :one
SELECT species FROM species_presence
WHERE lake_id = $1
ORDER BY confidence DESC, species
LIMIT 1
`

// The lake's most-confident present species — the default prediction target.
func (q *Queries) PrimarySpecies(ctx context.Context, lakeID int64) (string, error) {
	row := q.db.QueryRow(ctx, primarySpecies, lakeID)
	var species string
	err := row.Scan(&species)
	return species, err
}

const rebuildStockingPresence = `-- name: RebuildStockingPresence :exec
INSERT INTO species_presence (lake_id, species, confidence, source)
SELECT DISTINCT lake_id, species, 0.8, 'stocking'
FROM stocking_events
WHERE lake_id IS NOT NULL
ON CONFLICT (lake_id, species) DO UPDATE SET updated_at = now()
`

// Derive species presence from the stocking feed (knowledge base, not ML).
func (q *Queries) RebuildStockingPresence(ctx context.Context) error {
	_, err := q.db.Exec(ctx, rebuildStockingPresence)
	return err
}

const speciesForLake = `-- name: SpeciesForLake :many
SELECT species, confidence, source, updated_at
FROM species_presence
WHERE lake_id = $1
ORDER BY confidence DESC, species
`

type SpeciesForLakeRow struct {
	Species    string             `json:"species"`
	Confidence float64            `json:"confidence"`
	Source     string             `json:"source"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SpeciesForLake(ctx context.Context, lakeID int64) ([]SpeciesForLakeRow, error) {
	rows, err := q.db.Query(ctx, speciesForLake, lakeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpeciesForLakeRow
	for rows.Next() {
		var i SpeciesForLakeRow
		if err := rows.Scan(
			&i.Species,
			&i.Confidence,
			&i.Source,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
