// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stocking.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countStockingEvents = `-- name: CountStockingEvents :one
SELECT count(*) FROM stocking_events
`

func (q *Queries) CountStockingEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStockingEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertStockingEvent = `-- name: InsertStockingEvent :execrows
INSERT INTO stocking_events
    (lake_id, species, count, size_class, plant_date, hatchery, socrata_row_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (socrata_row_id) DO NOTHING
`

type InsertStockingEventParams struct {
	LakeID       *int64      `json:"lake_id"`
	Species      string      `json:"species"`
	Count        *int32      `json:"count"`
	SizeClass    *string     `json:"size_class"`
	PlantDate    pgtype.Date `json:"plant_date"`
	Hatchery     *string     `json:"hatchery"`
	SocrataRowID string      `json:"socrata_row_id"`
}

// Idempotent insert keyed on the Socrata row id (a content hash), so re-polling
// the same rows is a no-op. Returns rows affected: 1 = new, 0 = already seen.
func (q *Queries) InsertStockingEvent(ctx context.Context, arg InsertStockingEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertStockingEvent,
		arg.LakeID,
		arg.Species,
		arg.Count,
		arg.SizeClass,
		arg.PlantDate,
		arg.Hatchery,
		arg.SocrataRowID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
